FetchReach-v2:
  n_timesteps: !!float 20000
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  ent_coef: 'auto'
  batch_size: 256
  gamma: 0.95
  learning_rate: 0.001
  learning_starts: 1000
  normalize: True
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict(
    goal_selection_strategy='future',
    n_sampled_goal=4
  )"
  policy_kwargs: "dict(net_arch=[64, 64])"


HalfCheetah-v4: &pybullet-defaults
  # env_wrapper:
  #   - sb3_contrib.common.wrappers.TimeFeatureWrapper
  #   - rl_zoo3.wrappers.DelayedRewardWrapper:
  #       delay: 10
  #   - rl_zoo3.wrappers.HistoryWrapper:
  #       horizon: 10
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 300000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.98
  tau: 0.02
  train_freq: 8
  gradient_steps: 8
  learning_starts: 10000
  # replay_buffer_kwargs: "dict(handle_timeout_termination=True)"
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3, net_arch=[400, 300])"